esphome:
  name: d1-r2
  friendly_name: D1 R2 Door Sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "o39WwXlyWOWjOBva0BzYQj2/imZHseqYTUpKP8tVi20="

ota:
  platform: esphome
  password: "3582b0b9ae8efe8c28f21579af0663a7"

wifi:
  networks:
    - ssid: "ERROR404"
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "lansolo"
    password: !secret ap_password

captive_portal:

# HC-SR04 Ultrasonic Sensor Configuration
sensor:
  # Ultrasonic sensor setup
  - platform: ultrasonic
    trigger_pin: GPIO5  # D1 on most D1 R2 boards
    echo_pin: GPIO4     # D2 on most D1 R2 boards
    name: "Door Distance"
    update_interval: 1s
    unit_of_measurement: "cm"
    id: door_distance
    
  # LDR (Light Dependent Resistor) Setup
  - platform: adc
    pin: A0
    name: "Room Light Level"
    update_interval: 5s
    unit_of_measurement: "%"
    filters:
      - lambda: return (x / 1024.0) * 100.0; # Convert analog reading to percentage
    id: light_level

# Light control with relay
output:
  - platform: gpio
    pin: GPIO14  # D5 on most D1 R2 boards
    id: light_output

light:
  - platform: binary
    name: "Room Light"
    output: light_output
    id: room_light

# Simple mode switch to enable/disable automatic control
switch:
  - platform: template
    name: "Auto Light Control"
    id: auto_mode
    optimistic: true
    restore_mode: "RESTORE_DEFAULT_OFF"
